In [41]:
#import dependencies
import pandas as pd
import numpy as np

In [42]:
#load inbuit dataset
from sklearn.datasets import load_iris 

In [43]:
#variable assinging
df=load_iris()

In [44]:
df

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [45]:
#features names specification

print(df.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [46]:
#printing all the targeted values

print(df.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [47]:
#checking the tables columns and rows size of the targeted data

print(df.data.shape)

(150, 4)


In [48]:
#checking the tables columns and rows size of the targeted data

print(df.target.shape)

(150,)


In [49]:
#assigning data and target values to x and y variables

x=df.data
y=df.target

In [50]:
#method to train the data

from sklearn.model_selection import train_test_split


In [51]:
#size of the test values

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=10)

In [52]:
#length of trained data

len(x_train)

120

In [53]:
#length of test data

len(y_test)

30

# USING LOGISTIC REGRESSION MODEL FOR TESTING AND ACCURACY

In [63]:
#importing dependiencies

from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [55]:
#assigning a variable to logistsic regression method
Lr=LogisticRegression()

In [56]:
#fitting the model

Lr.fit(x_train,y_train)

LogisticRegression()

In [67]:
#predict the test values

ypred=Lr.predict(x_test)
ypred

array([1, 2, 0, 1, 0, 1, 1, 1, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2,
       2, 0, 1, 0, 1, 1, 1, 2])

In [60]:
#optional method

Lr.predict(x_test)

array([1, 2, 0, 1, 0, 1, 1, 1, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2,
       2, 0, 1, 0, 1, 1, 1, 2])

In [70]:
#accuray testes:

print(metrics.accuracy_score(y_test,ypred)*100)

100.0


In [ ]:
xpred=Lr.predict()

In [19]:
#formula to find the accuracy

Lr.score(x_train,y_train)*100      #accuray of trained data is 97.5 out of 100

97.5

In [20]:
Lr.score(x_test,y_test)*100       #accuray of tested data is 100 out of 100

100.0

# USING K NEAREST NEIGHBOR METHOD FOR TESTING AND ACCURACY

In [21]:
#importing dependiencies

from sklearn.neighbors import KNeighborsClassifier

In [22]:
#assing a variable and neighbor with 1 which compares the given input with the most suitable table values

knn=KNeighborsClassifier(n_neighbors=1)

In [23]:
print(knn)

KNeighborsClassifier(n_neighbors=1)


In [24]:
#fit the model

knn.fit(x,y)

KNeighborsClassifier(n_neighbors=1)

In [25]:
#predict the input values eith dimension of 2

knn.predict([[3,5,4,2]])

array([2])

In [26]:
#predicat the values of more than one input values

x_new=[[3,5,4,2],[5,4,3,2]]
knn.predict(x_new)

array([2, 1])

In [30]:
knn=KNeighborsClassifier(n_neighbors=1)
knn.fit(x,y)
knn.predict(x_new)

array([2, 1])

In [31]:
#test the accuracy

knn.score(x,y)*100

100.0

In [27]:
#assing a variable and neighbor with 5 which compares the value with the suitables comparision of 5

knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x,y)
knn.predict(x_new)


array([1, 1])

In [29]:
#accuracy of neighbor 5

knn.score(x,y)*100

96.66666666666667

In [75]:
#checking accuracy to specified number of inputs

krange=range(1,26)
score=[]
for k in krange:
    knn=KNeighborsClassifier(n_neighbors=k)
    knn.fit(x_train,y_train)
    pred=knn.predict(x_test)
    print(metrics.accuracy_score(y_test,pred)*100)

96.66666666666667
96.66666666666667
96.66666666666667
96.66666666666667
96.66666666666667
96.66666666666667
96.66666666666667
100.0
100.0
100.0
100.0
100.0
100.0
100.0
100.0
100.0
96.66666666666667
96.66666666666667
100.0
100.0
100.0
96.66666666666667
96.66666666666667
96.66666666666667
96.66666666666667
